server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/super_shop
    username: ${LOCAL_USERNAME}
    password: ${LOCAL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret: ${SECRET_KEY}
    token:
      access-expiration-time: 43200000    # 12시간
      refresh-expiration-time: 604800000